version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
      time: "09:00"
    allow:
      - dependency-type: "direct"
    groups:
      react-ecosystem:
        patterns: 
          - "react*"
          - "@types/react*"
          - "react-dom"
          - "@types/react-dom"
        update-types:
          - "minor"
          - "patch"
    labels:
      - "dependencies"
    commit-message:
      prefix: "deps"
      include: "scope"
    rebase-strategy: "auto" 
