name: E2E Tests on Deploy

on:
  workflow_run:
    workflows: ["Deploy to GitHub Pages"]
    types:
      - completed
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'index.html'
      - 'package*.json'
      - 'vite.config.ts'

jobs:
  e2e-tests-live:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    # Run this job regardless of whether the deploy was successful or not
    # This way we can catch issues even if deploy was cancelled
    if: always()
    
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Wait for deployment to be available
      run: |
        echo "Waiting for site to be available..."
        for i in {1..10}; do
          if curl -f --connect-timeout 10 --max-time 30 -s https://sylhare.github.io/Badminton/ > /dev/null; then
            echo "Site is available!"
            break
          fi
          echo "Attempt $i failed, waiting 30s..."
          sleep 30
        done

    - name: Run Playwright tests against live site
      run: npm run test:e2e
      env:
        E2E_BASE_URL: https://sylhare.github.io/Badminton

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report-live
        path: playwright-report/
        retention-days: 30

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-live
        path: test-results/
        retention-days: 30
        
    - name: Create issue on failure
      if: failure()
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'E2E Tests Failed on Live Site',
            body: `The E2E tests have failed on the live site after deployment.
            
            **Workflow Run:** ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            **Commit:** ${{ github.sha }}
            **Branch:** ${{ github.ref_name }}
            
            Please check the test artifacts and fix any issues.`,
            labels: ['bug', 'e2e-failure']
          })
